---
all:
  vars:
    ansible_user: admin
    ansible_password: "{{ vault_admin_password }}"
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_common_args: >-
      -o KexAlgorithms=+diffie-hellman-group14-sha1
      -o HostKeyAlgorithms=+ssh-rsa
      -o Ciphers=+aes256-cbc
      -o MACs=+hmac-sha1
  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.100.10
          ospf_router_id: 1.1.1.1
        R2:
          ansible_host: 192.168.100.11
          ospf_router_id: 2.2.2.2
        R3:
          ansible_host: 192.168.100.12
          ospf_router_id: 3.3.3.3
        R4:
          ansible_host: 192.168.100.13
          ospf_router_id: 4.4.4.4
          bgp_local_as: 65001
          bgp_router_id: 4.4.4.4
          bgp_peer_ip: 203.0.113.2
          bgp_peer_as: 65000
          bgp_peer_description: ISP-R7
          bgp_network: 10.0.0.0
          bgp_mask: 255.255.0.0
        R8:
          ansible_host: 192.168.100.17
          ospf_router_id: 8.8.8.8
    branch:
      hosts:
        R5:
          ansible_host: 192.168.100.16
          ospf_router_id: 5.5.5.5
        R6:
          ansible_host: 192.168.100.15
          ospf_router_id: 6.6.6.6
    isp:
      hosts:
        R7:
          ansible_host: 192.168.100.14
