---
- name: Configure ACLs from policy data
  cisco.ios.ios_config:
    lines: >
      {{ acl_rule.sequence }} {{ acl_rule.action }}
      {{ acl_rule.source | default('') }}
      {{ acl_rule.destination | default('') }}
      {{ 'log' if acl_rule.log | default(false) else '' }}
    parents: "ip access-list {{ acl.type }} {{ acl.name }}"
  loop: "{{ ios_security_acl_policy }}"
  loop_control:
    loop_var: acl

- name: Apply MGMT-ACCESS to VTY lines
  cisco.ios.ios_config:
    lines:
      - access-class MGMT-ACCESS in
    parents: line vty 0 4

- name: Block attacker R5 SSH traffic
  cisco.ios.ios_config:
    lines:
      - 5 deny tcp host 10.0.34.5 any eq 22 log
    parents: ip access-list extended INBOUND-POLICY

- name: Block Operations to Finance MySQL
  cisco.ios.ios_config:
    lines:
      - 10 deny tcp 10.2.0.0 0.0.0.255 10.1.0.0 0.0.0.255 eq 3306 log
      - 20 permit ip 10.2.0.0 0.0.0.255 any
    parents: ip access-list extended 102

- name: Apply Operations ACL to VLAN 20 subinterface
  cisco.ios.ios_config:
    lines:
      - ip access-group 102 in
    parents: interface FastEthernet1/0.20
